BillingSystem/BillingSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('logs.urls')),
    path('admin/', admin.site.urls),
    # path('logs/index.html',include())
]

BillingSystem/logs/urls.py
from django.urls import path
from . import views

app_name = 'logs'

urlpatterns = [
    path('print_details',views.print_details,name='print_details'),
    path('',views.home_page,name='home_page'),
    
    # path('',views.requestData,name='requestData'),
]

BillingSystem/logs/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

class Firm(models.Model):
    firm_name = models.CharField(max_length = 200,primary_key=True,unique=True)
    gstin = models.CharField(max_length= 15,blank=True)
    date = models.DateField(editable=False,default=timezone.now)
    def __str__(self):
        return self.firm_name

    def clean(self):
        self.firm_name = self.firm_name.upper()
        auto_now_add = False
        # self.date = timezone.now
    
    class Meta:
        ordering = ['firm_name']

class Entry(models.Model):
    firm_name = models.ForeignKey(Firm,on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    size_range = [
        ('1.0','1.0'),
        ('1.5','1.5'),
        ('2.0','2.0'),
        ('2.5','2.5'),
        ('3.0','3.0'),
        ('4.0','4.0'),
        ('5.0','5.0'),
        ('6.0','6.0'),
    ]
    size = models.CharField(max_length = 3,choices=size_range)
    weight = models.DecimalField(max_digits = 10 , decimal_places=3,validators=[
        MinValueValidator(1)
    ])
    quantity = models.IntegerField(default=0)
    making = (
        (u'Framed',u'Framed'),
        (u'Sticked',u'Sticked')
    )
    making_type = models.CharField(max_length=10,choices=making)
    remarks = models.CharField(max_length=100,blank=True)
    def __str__(self):
        return str(self.firm_name)

BillingSystem/logs/forms.py
from django.shortcuts import render

# Create your views here.
from django.http import  HttpResponse
from .models import Entry,Firm
from django import forms
from django.forms import ModelChoiceField , widgets , SelectDateWidget
from django.forms.fields import *
from django.contrib.admin.widgets import AdminDateWidget
from datetime import date
from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError

class NameForm(forms.Form):
    queryset = Firm.objects.all()
    firm_name = ModelChoiceField(queryset=queryset)
    start_date = DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    end_date = DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    
    def clean(self):
        # cleaned_data = super().clean()
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        
        today_date = date.today()

        if start_date>today_date and end_date>today_date:
            #self._errors['firm_name']=[u"Start and end date can't exceed todays's date." ]
            raise forms.ValidationError(_("Start and end date can't exceed today's date."))
        elif start_date>today_date:
            raise forms.ValidationError(_("Start date can't exceed today's date."))
            #self._errors['firm_name']=[u"Start date can't exceed today's date." ]
        elif end_date > today_date:
            #self._errors['firm_name']=[u"End date can't exceed today's date." ]
            raise forms.ValidationError(_("End date can't exceed today's date."))
        elif(end_date < start_date):
            #self._errors['firm_name']=[u"End date must be greater than start date." ]
            raise ValidationError(_("Start date must be greater than today's date."))
        
        return self.cleaned_data

BillingSystem/logs/views.py
from django.db.models.query import NamedValuesListIterable
from django.shortcuts import render
from django.http import  HttpResponse
from .models import Entry,Firm
from django import forms
from django.forms import ModelChoiceField
from .forms import NameForm
from .utils import generateExcel
from django.contrib import messages

def print_details(request):
    name =''
    # request.session.set_expiry(120)
    form = NameForm
    if request.method=='POST':
        form = NameForm(request.POST)
        if(form.is_valid()):
            name = form.cleaned_data['firm_name']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            print(name,start_date,end_date)
            data = Entry.objects.filter(firm_name=name,date__range=[start_date,end_date])
            if(data.count()==0): 
                print("No data found")
                return render(request,'logs/print_details.html',{'form':form})
            else: generateExcel(data,name,start_date,end_date)
            # for i in data:
            #     print(str(i.date)+" "+str(i.firm_name)+" "+str(i.quantity)+" "+str(i.weight)+" "+str(i.remarks))
    return render(request,'logs/print_details.html',{'form':form})


def home_page(request):
    return render(request,'logs/home_page.html')

BillingSystem/logs/templates/logs/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <style type="text/css">
        #FirmName{
            color: black;
            size: 20px;
            text-align: center;
            font-weight: 100;
            padding: 80px 0px 20px 0px;
        }
        body{
            background-color: beige;
            text-align: center;
        }
        #link1{
            color:lightcoral;
        }

    </style>
</head>
<body>
    <div id="FirmName">
        Hello From Sadiq's Firm
    </div>
    <a href="http://127.0.0.1:8000/print_details"
            style="font-family:Helvetica,Arial,sans-serif;
                    line-height:16px;color:#ffffff;
                    font-weight:400;
                    text-decoration:none;
                    font-size:14px;
                    display:inline-block;
                    padding:10px 24px;
                    background-color:#4184f3;
                    border-radius:5px;
                    min-width:90px" >
            Print Details</a>
        
        <br><br>
        <a href="http://127.0.0.1:8000/admin" 
        style="font-family:Helvetica,Arial,sans-serif;
                line-height:16px;color:#ffffff;
                font-weight:400;
                text-decoration:none;font-size:14px;display:inline-block;padding:10px 24px;background-color:#4184f3;border-radius:5px;min-width:90px">
        Admin page</a> 
</body>
</html>

BillingSystem/logs/templates/logs/print_details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        /* table tr:nth-child(1) {
            visibility: collapse;
        } */
        .FirmName{
            color: black;
            size: 12px;
            text-align: center;
            font-weight: 100;
            /* padding: px 0px 0px 0px; */
            margin-top: 40px;
            margin-bottom: 10px;
        }
        table, body, p, h2, td, form,ul{
            text-align: center;
            font-style: aerial;
        }
        #head1{
            text-align: center;
            margin: 30px 0px 20px 0px ;
            font-weight: bold;
            font-size: 22px;
            color: rgb(22, 21, 112);
            border: 3px solid;
            border-radius: 12px;
            border-color: black;
            min-width: 90px;
            padding: 5px;
            border-color: white;
            background-color:cornflowerblue;
            border-color: black;
            display:inline-block;
        }
        #button_text{
            min-width:90px;
            color: rgb(44, 13, 114);
            background-color: wheat;
            border: 12px;
            border-radius: 12px;
            font-size: 19px;
            height: 40px;
            width: 100px;
            margin: 10px;
            font-weight: bold;
            background-color: beige;
            display:inline-block;
            text-decoration: none;       
        }
        .messages{
            color: crimson;
            font-size: 22px;
            margin-top: 30px;
            font-weight: bold;
            font-family: Arial, Helvetica, sans-serif;
            width: 200px;
            height: 26px;
            border: 3px solid blue; 
            align-items: center;
            align-self: center;
            border-radius: 10px;
            padding: 1px;
            box-sizing: content-box;
        }
        #link1{
            color:rgb(1, 0, 3);
        }
        #id_start_date,#id_end_date,#id_firm_name{
            color: rgb(0, 4, 253);
            background-color: wheat;
            width: 88%;
        }
    </style>
    <title>Print Details</title>
    
</head>
<body style="background-color:rgb(0, 255, 255)">
    <!-- <script type="text/javascript">
        alert('{{message}}'); -->
    <!-- </script> -->
    {% if messages %}
    <div class="messages" >
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    <p id="head1" align="center">Fill the details to be printed</p>
    {{form.non_field_errors}}
    <form method="post">
        {% csrf_token %}
        <table align="center" style="padding: 0px;font-size: 18px;line-height: 30px;color: black;">
            {{ form.as_table }}
        </table>
        <button type="submit" id="button_text" target="_blank" >Submit</button>
    </form>
    <div>
        <!-- <button type="button" href="http://127.0.0.1:8000/admin">Home Page</button> -->
        
        <a href="http://127.0.0.1:8000" 
            style="font-family:Helvetica,Arial,sans-serif;
                    line-height:16px;color:#ffffff;
                    font-weight:400;
                    text-decoration:none;
                    font-size:14px;
                    display:inline-block;
                    padding:10px 24px;
                    background-color:#4184f3;
                    border-radius:5px;
                    min-width:90px" >
            Home page</a>
        
        <br><br>
        <a href="http://127.0.0.1:8000/admin" 
        style="font-family:Helvetica,Arial,sans-serif;
                line-height:16px;color:#ffffff;
                font-weight:400;
                text-decoration:none;font-size:14px;display:inline-block;padding:10px 24px;background-color:#4184f3;border-radius:5px;min-width:90px">
        Admin page</a>
    </div>
</body>

</html>

BillingSystem/logs/templates/logs/temp.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        table tr:nth-child(1) {
            visibility: collapse;
        }
        .FirmName{
            color: black;
            size: 12px;
            text-align: center;
            font-weight: 100;
            padding: 40px 0px 0px 0px;
        }
        table, body, p, h2, td, form{
            text-align: center;
            align : "center"
        }
        #head1{
            text-align: center;
            margin: 80px 0px 0px 0px ;
            font-weight: 400;
            font-size: 22px;
            color: rgb(22, 21, 112);
        }
        #button1{
            color: rgb(44, 13, 114);
            background-color: wheat;
            border: 12px;
            border-radius: 12px;
            font-size: 19px;
            height: 40px;
            width: 100px;
            margin: 10px;
            font-weight: 600;
        }
    </style>
    <title>Print Details</title>
</head>

<body style="background-color: burlywood;">

    <p id="head1">Fill the details to be printed</p>
    {{form.non_field_errors}}
    <form method="post">
        {% csrf_token %}
        <table align="center" style="padding: 0px;font-size: 18px;">
            {{ form.as_table }}
        </table>
        <button type="submit" id="button1">Submit</button>
    </form>
</body>

</html>